package stream

// Define all log tags.
// It was used by SJTU-OpenNetwotk/go-logparser

const (
	TAG_WORKERSTART = "WORKERSTART"
	TAG_WORKEREND = "WORKEREND"
	TAG_BLOCKSEND = "BLOCKSEND"
	TAG_BLOCKRECEIVE = "BLOCKRECV"
	TAG_STREAMREQUEST = "STREAMREQUEST"
	TAG_STREAMUNSUBSCRIBE = "STREAMUNSUBSCRIBE"
	TAG_STREAMRESPONSE = "STREAMRESPONSE"
	TAG_WORKERSTORE_REMOVE = "WORKERREMOVE"
	TAG_WORKERSTORE_ADD = "WORKERADD"
)
