// Code generated by protoc-gen-go. DO NOT EDIT.
// source: model.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type StreamMeta_Type int32

const (
	StreamMeta_FILE    StreamMeta_Type = 0
	StreamMeta_PICTURE StreamMeta_Type = 1
	StreamMeta_VIDEO   StreamMeta_Type = 2
)

var StreamMeta_Type_name = map[int32]string{
	0: "FILE",
	1: "PICTURE",
	2: "VIDEO",
}

var StreamMeta_Type_value = map[string]int32{
	"FILE":    0,
	"PICTURE": 1,
	"VIDEO":   2,
}

func (x StreamMeta_Type) String() string {
	return proto.EnumName(StreamMeta_Type_name, int32(x))
}

func (StreamMeta_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_4c16552f9fdb66d8, []int{2, 0}
}

type Notification_Type int32

const (
	Notification_INVITE_RECEIVED     Notification_Type = 0
	Notification_ACCOUNT_PEER_JOINED Notification_Type = 1
	Notification_ACCOUNT_PEER_LEFT   Notification_Type = 8
	Notification_PEER_JOINED         Notification_Type = 2
	Notification_PEER_LEFT           Notification_Type = 3
	Notification_MESSAGE_ADDED       Notification_Type = 4
	Notification_FILES_ADDED         Notification_Type = 5
	Notification_COMMENT_ADDED       Notification_Type = 6
	Notification_LIKE_ADDED          Notification_Type = 7
	Notification_ADMIN_ADDED         Notification_Type = 100
	Notification_PEER_REMOVED        Notification_Type = 101
	Notification_VIDEO_ADDED         Notification_Type = 102
	Notification_STREAM_ADDED        Notification_Type = 103
	Notification_SIMPLEFILE_ADDED    Notification_Type = 104
	Notification_STREAM_FILE         Notification_Type = 500
	Notification_RECORD_REPORT       Notification_Type = 501
)

var Notification_Type_name = map[int32]string{
	0:   "INVITE_RECEIVED",
	1:   "ACCOUNT_PEER_JOINED",
	8:   "ACCOUNT_PEER_LEFT",
	2:   "PEER_JOINED",
	3:   "PEER_LEFT",
	4:   "MESSAGE_ADDED",
	5:   "FILES_ADDED",
	6:   "COMMENT_ADDED",
	7:   "LIKE_ADDED",
	100: "ADMIN_ADDED",
	101: "PEER_REMOVED",
	102: "VIDEO_ADDED",
	103: "STREAM_ADDED",
	104: "SIMPLEFILE_ADDED",
	500: "STREAM_FILE",
	501: "RECORD_REPORT",
}

var Notification_Type_value = map[string]int32{
	"INVITE_RECEIVED":     0,
	"ACCOUNT_PEER_JOINED": 1,
	"ACCOUNT_PEER_LEFT":   8,
	"PEER_JOINED":         2,
	"PEER_LEFT":           3,
	"MESSAGE_ADDED":       4,
	"FILES_ADDED":         5,
	"COMMENT_ADDED":       6,
	"LIKE_ADDED":          7,
	"ADMIN_ADDED":         100,
	"PEER_REMOVED":        101,
	"VIDEO_ADDED":         102,
	"STREAM_ADDED":        103,
	"SIMPLEFILE_ADDED":    104,
	"STREAM_FILE":         500,
	"RECORD_REPORT":       501,
}

func (x Notification_Type) String() string {
	return proto.EnumName(Notification_Type_name, int32(x))
}

func (Notification_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_4c16552f9fdb66d8, []int{5, 0}
}

// StreamBlock is the meta data of a block
// The descriptin stores the complete file name
type StreamBlock struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Streamid             string   `protobuf:"bytes,2,opt,name=streamid,proto3" json:"streamid,omitempty"`
	Index                uint64   `protobuf:"varint,3,opt,name=index,proto3" json:"index,omitempty"`
	Size                 int32    `protobuf:"varint,4,opt,name=size,proto3" json:"size,omitempty"`
	IsRoot               bool     `protobuf:"varint,5,opt,name=isRoot,proto3" json:"isRoot,omitempty"`
	Description          string   `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StreamBlock) Reset()         { *m = StreamBlock{} }
func (m *StreamBlock) String() string { return proto.CompactTextString(m) }
func (*StreamBlock) ProtoMessage()    {}
func (*StreamBlock) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c16552f9fdb66d8, []int{0}
}

func (m *StreamBlock) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StreamBlock.Unmarshal(m, b)
}
func (m *StreamBlock) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StreamBlock.Marshal(b, m, deterministic)
}
func (m *StreamBlock) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StreamBlock.Merge(m, src)
}
func (m *StreamBlock) XXX_Size() int {
	return xxx_messageInfo_StreamBlock.Size(m)
}
func (m *StreamBlock) XXX_DiscardUnknown() {
	xxx_messageInfo_StreamBlock.DiscardUnknown(m)
}

var xxx_messageInfo_StreamBlock proto.InternalMessageInfo

func (m *StreamBlock) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *StreamBlock) GetStreamid() string {
	if m != nil {
		return m.Streamid
	}
	return ""
}

func (m *StreamBlock) GetIndex() uint64 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *StreamBlock) GetSize() int32 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *StreamBlock) GetIsRoot() bool {
	if m != nil {
		return m.IsRoot
	}
	return false
}

func (m *StreamBlock) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

type StreamBlockList struct {
	Items                []*StreamBlock `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *StreamBlockList) Reset()         { *m = StreamBlockList{} }
func (m *StreamBlockList) String() string { return proto.CompactTextString(m) }
func (*StreamBlockList) ProtoMessage()    {}
func (*StreamBlockList) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c16552f9fdb66d8, []int{1}
}

func (m *StreamBlockList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StreamBlockList.Unmarshal(m, b)
}
func (m *StreamBlockList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StreamBlockList.Marshal(b, m, deterministic)
}
func (m *StreamBlockList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StreamBlockList.Merge(m, src)
}
func (m *StreamBlockList) XXX_Size() int {
	return xxx_messageInfo_StreamBlockList.Size(m)
}
func (m *StreamBlockList) XXX_DiscardUnknown() {
	xxx_messageInfo_StreamBlockList.DiscardUnknown(m)
}

var xxx_messageInfo_StreamBlockList proto.InternalMessageInfo

func (m *StreamBlockList) GetItems() []*StreamBlock {
	if m != nil {
		return m.Items
	}
	return nil
}

type StreamMeta struct {
	Id                   string          `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Nsubstreams          int32           `protobuf:"varint,2,opt,name=nsubstreams,proto3" json:"nsubstreams,omitempty"`
	Bitrate              int32           `protobuf:"varint,3,opt,name=bitrate,proto3" json:"bitrate,omitempty"`
	Caption              string          `protobuf:"bytes,4,opt,name=caption,proto3" json:"caption,omitempty"`
	Nblocks              uint64          `protobuf:"varint,5,opt,name=nblocks,proto3" json:"nblocks,omitempty"`
	Posterid             string          `protobuf:"bytes,6,opt,name=posterid,proto3" json:"posterid,omitempty"`
	Type                 StreamMeta_Type `protobuf:"varint,7,opt,name=type,proto3,enum=StreamMeta_Type" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *StreamMeta) Reset()         { *m = StreamMeta{} }
func (m *StreamMeta) String() string { return proto.CompactTextString(m) }
func (*StreamMeta) ProtoMessage()    {}
func (*StreamMeta) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c16552f9fdb66d8, []int{2}
}

func (m *StreamMeta) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StreamMeta.Unmarshal(m, b)
}
func (m *StreamMeta) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StreamMeta.Marshal(b, m, deterministic)
}
func (m *StreamMeta) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StreamMeta.Merge(m, src)
}
func (m *StreamMeta) XXX_Size() int {
	return xxx_messageInfo_StreamMeta.Size(m)
}
func (m *StreamMeta) XXX_DiscardUnknown() {
	xxx_messageInfo_StreamMeta.DiscardUnknown(m)
}

var xxx_messageInfo_StreamMeta proto.InternalMessageInfo

func (m *StreamMeta) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *StreamMeta) GetNsubstreams() int32 {
	if m != nil {
		return m.Nsubstreams
	}
	return 0
}

func (m *StreamMeta) GetBitrate() int32 {
	if m != nil {
		return m.Bitrate
	}
	return 0
}

func (m *StreamMeta) GetCaption() string {
	if m != nil {
		return m.Caption
	}
	return ""
}

func (m *StreamMeta) GetNblocks() uint64 {
	if m != nil {
		return m.Nblocks
	}
	return 0
}

func (m *StreamMeta) GetPosterid() string {
	if m != nil {
		return m.Posterid
	}
	return ""
}

func (m *StreamMeta) GetType() StreamMeta_Type {
	if m != nil {
		return m.Type
	}
	return StreamMeta_FILE
}

type StreamMetaList struct {
	Items                []*StreamMeta `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *StreamMetaList) Reset()         { *m = StreamMetaList{} }
func (m *StreamMetaList) String() string { return proto.CompactTextString(m) }
func (*StreamMetaList) ProtoMessage()    {}
func (*StreamMetaList) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c16552f9fdb66d8, []int{3}
}

func (m *StreamMetaList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StreamMetaList.Unmarshal(m, b)
}
func (m *StreamMetaList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StreamMetaList.Marshal(b, m, deterministic)
}
func (m *StreamMetaList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StreamMetaList.Merge(m, src)
}
func (m *StreamMetaList) XXX_Size() int {
	return xxx_messageInfo_StreamMetaList.Size(m)
}
func (m *StreamMetaList) XXX_DiscardUnknown() {
	xxx_messageInfo_StreamMetaList.DiscardUnknown(m)
}

var xxx_messageInfo_StreamMetaList proto.InternalMessageInfo

func (m *StreamMetaList) GetItems() []*StreamMeta {
	if m != nil {
		return m.Items
	}
	return nil
}

// [deprecated] use streamMeta directly
type Stream struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Stream) Reset()         { *m = Stream{} }
func (m *Stream) String() string { return proto.CompactTextString(m) }
func (*Stream) ProtoMessage()    {}
func (*Stream) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c16552f9fdb66d8, []int{4}
}

func (m *Stream) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Stream.Unmarshal(m, b)
}
func (m *Stream) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Stream.Marshal(b, m, deterministic)
}
func (m *Stream) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Stream.Merge(m, src)
}
func (m *Stream) XXX_Size() int {
	return xxx_messageInfo_Stream.Size(m)
}
func (m *Stream) XXX_DiscardUnknown() {
	xxx_messageInfo_Stream.DiscardUnknown(m)
}

var xxx_messageInfo_Stream proto.InternalMessageInfo

func (m *Stream) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

// Copied from hon-textile/pb/protos/model.proto
// In a shadow peer, Notification is used only for statistic sent to other peer.
type Notification struct {
	Id          string               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Date        *timestamp.Timestamp `protobuf:"bytes,2,opt,name=date,proto3" json:"date,omitempty"`
	Actor       string               `protobuf:"bytes,3,opt,name=actor,proto3" json:"actor,omitempty"`
	Subject     string               `protobuf:"bytes,4,opt,name=subject,proto3" json:"subject,omitempty"`
	SubjectDesc string               `protobuf:"bytes,5,opt,name=subject_desc,json=subjectDesc,proto3" json:"subject_desc,omitempty"`
	Block       string               `protobuf:"bytes,6,opt,name=block,proto3" json:"block,omitempty"`
	Target      string               `protobuf:"bytes,7,opt,name=target,proto3" json:"target,omitempty"`
	Type        Notification_Type    `protobuf:"varint,8,opt,name=type,proto3,enum=Notification_Type" json:"type,omitempty"`
	Body        string               `protobuf:"bytes,9,opt,name=body,proto3" json:"body,omitempty"`
	Read        bool                 `protobuf:"varint,10,opt,name=read,proto3" json:"read,omitempty"`
	// view info
	User                 *User    `protobuf:"bytes,101,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Notification) Reset()         { *m = Notification{} }
func (m *Notification) String() string { return proto.CompactTextString(m) }
func (*Notification) ProtoMessage()    {}
func (*Notification) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c16552f9fdb66d8, []int{5}
}

func (m *Notification) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Notification.Unmarshal(m, b)
}
func (m *Notification) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Notification.Marshal(b, m, deterministic)
}
func (m *Notification) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Notification.Merge(m, src)
}
func (m *Notification) XXX_Size() int {
	return xxx_messageInfo_Notification.Size(m)
}
func (m *Notification) XXX_DiscardUnknown() {
	xxx_messageInfo_Notification.DiscardUnknown(m)
}

var xxx_messageInfo_Notification proto.InternalMessageInfo

func (m *Notification) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Notification) GetDate() *timestamp.Timestamp {
	if m != nil {
		return m.Date
	}
	return nil
}

func (m *Notification) GetActor() string {
	if m != nil {
		return m.Actor
	}
	return ""
}

func (m *Notification) GetSubject() string {
	if m != nil {
		return m.Subject
	}
	return ""
}

func (m *Notification) GetSubjectDesc() string {
	if m != nil {
		return m.SubjectDesc
	}
	return ""
}

func (m *Notification) GetBlock() string {
	if m != nil {
		return m.Block
	}
	return ""
}

func (m *Notification) GetTarget() string {
	if m != nil {
		return m.Target
	}
	return ""
}

func (m *Notification) GetType() Notification_Type {
	if m != nil {
		return m.Type
	}
	return Notification_INVITE_RECEIVED
}

func (m *Notification) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

func (m *Notification) GetRead() bool {
	if m != nil {
		return m.Read
	}
	return false
}

func (m *Notification) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type User struct {
	Address              string   `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Avatar               string   `protobuf:"bytes,3,opt,name=avatar,proto3" json:"avatar,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c16552f9fdb66d8, []int{6}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *User) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *User) GetAvatar() string {
	if m != nil {
		return m.Avatar
	}
	return ""
}

func init() {
	proto.RegisterEnum("StreamMeta_Type", StreamMeta_Type_name, StreamMeta_Type_value)
	proto.RegisterEnum("Notification_Type", Notification_Type_name, Notification_Type_value)
	proto.RegisterType((*StreamBlock)(nil), "StreamBlock")
	proto.RegisterType((*StreamBlockList)(nil), "StreamBlockList")
	proto.RegisterType((*StreamMeta)(nil), "StreamMeta")
	proto.RegisterType((*StreamMetaList)(nil), "StreamMetaList")
	proto.RegisterType((*Stream)(nil), "Stream")
	proto.RegisterType((*Notification)(nil), "Notification")
	proto.RegisterType((*User)(nil), "User")
}

func init() { proto.RegisterFile("model.proto", fileDescriptor_4c16552f9fdb66d8) }

var fileDescriptor_4c16552f9fdb66d8 = []byte{
	// 754 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x94, 0xcd, 0x6e, 0xe3, 0x36,
	0x14, 0x85, 0x47, 0xb6, 0xe4, 0x9f, 0x2b, 0xc7, 0xd1, 0x70, 0xa6, 0x53, 0x35, 0x28, 0x50, 0x8d,
	0x50, 0x14, 0x5e, 0x69, 0x80, 0x0c, 0xfa, 0x00, 0x8e, 0xc5, 0x14, 0x6a, 0x2d, 0xdb, 0xa0, 0x95,
	0x2c, 0xba, 0x31, 0x24, 0x8b, 0x71, 0x99, 0xda, 0x96, 0x20, 0xd2, 0x45, 0xd2, 0x77, 0xe9, 0x5b,
	0xf4, 0xc5, 0x0a, 0xb4, 0x40, 0x97, 0x05, 0x29, 0x2a, 0x51, 0xd2, 0x1d, 0xcf, 0xb9, 0x97, 0x22,
	0xef, 0xc7, 0x03, 0x81, 0x7d, 0x28, 0x72, 0xba, 0x0f, 0xca, 0xaa, 0x10, 0xc5, 0xc5, 0x37, 0xbb,
	0xa2, 0xd8, 0xed, 0xe9, 0x27, 0xa5, 0xb2, 0xd3, 0xdd, 0x27, 0xc1, 0x0e, 0x94, 0x8b, 0xf4, 0x50,
	0xd6, 0x0d, 0xfe, 0x1f, 0x06, 0xd8, 0x6b, 0x51, 0xd1, 0xf4, 0x70, 0xb5, 0x2f, 0xb6, 0xbf, 0xa2,
	0x31, 0x74, 0x58, 0xee, 0x1a, 0x9e, 0x31, 0x19, 0x92, 0x0e, 0xcb, 0xd1, 0x05, 0x0c, 0xb8, 0x2a,
	0xb3, 0xdc, 0xed, 0x28, 0xf7, 0x49, 0xa3, 0xf7, 0x60, 0xb1, 0x63, 0x4e, 0x1f, 0xdc, 0xae, 0x67,
	0x4c, 0x4c, 0x52, 0x0b, 0x84, 0xc0, 0xe4, 0xec, 0x77, 0xea, 0x9a, 0x9e, 0x31, 0xb1, 0x88, 0x5a,
	0xa3, 0x0f, 0xd0, 0x63, 0x9c, 0x14, 0x85, 0x70, 0x2d, 0xcf, 0x98, 0x0c, 0x88, 0x56, 0xc8, 0x03,
	0x3b, 0xa7, 0x7c, 0x5b, 0xb1, 0x52, 0xb0, 0xe2, 0xe8, 0xf6, 0xd4, 0x01, 0x6d, 0xcb, 0xff, 0x1e,
	0xce, 0x5b, 0xd7, 0x9b, 0x33, 0x2e, 0x90, 0x0f, 0x16, 0x13, 0xf4, 0xc0, 0x5d, 0xc3, 0xeb, 0x4e,
	0xec, 0xcb, 0x51, 0xd0, 0x6a, 0x20, 0x75, 0xc9, 0xff, 0xd7, 0x00, 0xa8, 0xed, 0x98, 0x8a, 0xf4,
	0x7f, 0x53, 0x79, 0x60, 0x1f, 0xf9, 0x29, 0xab, 0x27, 0xe1, 0x6a, 0x30, 0x8b, 0xb4, 0x2d, 0xe4,
	0x42, 0x3f, 0x63, 0xa2, 0x4a, 0x05, 0x55, 0xd3, 0x59, 0xa4, 0x91, 0xb2, 0xb2, 0x4d, 0xeb, 0xfb,
	0x9a, 0xea, 0x83, 0x8d, 0x94, 0x95, 0x63, 0x26, 0x6f, 0xc1, 0xd5, 0x98, 0x26, 0x69, 0xa4, 0xa4,
	0x58, 0x16, 0x5c, 0xd0, 0x8a, 0xe5, 0x7a, 0xc8, 0x27, 0x8d, 0xbe, 0x05, 0x53, 0x3c, 0x96, 0xd4,
	0xed, 0x7b, 0xc6, 0x64, 0x7c, 0xe9, 0x04, 0xcf, 0xd7, 0x0e, 0x92, 0xc7, 0x92, 0x12, 0x55, 0xf5,
	0x27, 0x60, 0x4a, 0x85, 0x06, 0x60, 0x5e, 0x47, 0x73, 0xec, 0xbc, 0x41, 0x36, 0xf4, 0x57, 0xd1,
	0x2c, 0xb9, 0x21, 0xd8, 0x31, 0xd0, 0x10, 0xac, 0xdb, 0x28, 0xc4, 0x4b, 0xa7, 0xe3, 0x7f, 0x86,
	0xf1, 0xf3, 0x27, 0x14, 0xb0, 0x8f, 0x2f, 0x81, 0xd9, 0xad, 0x23, 0x1a, 0x5e, 0x2e, 0xf4, 0x6a,
	0xf3, 0x35, 0x2a, 0xff, 0x2f, 0x13, 0x46, 0x8b, 0x42, 0xb0, 0x3b, 0xb6, 0x4d, 0xd5, 0x94, 0xaf,
	0x59, 0x06, 0x60, 0xe6, 0x12, 0x93, 0x84, 0x68, 0x5f, 0x5e, 0x04, 0x75, 0xe2, 0x82, 0x26, 0x71,
	0x41, 0xd2, 0x24, 0x8e, 0xa8, 0x3e, 0x99, 0x9a, 0x74, 0x2b, 0x8a, 0x4a, 0x71, 0x1d, 0x92, 0x5a,
	0x48, 0x76, 0xfc, 0x94, 0xdd, 0xd3, 0xad, 0x68, 0xa8, 0x6a, 0x89, 0x3e, 0xc2, 0x48, 0x2f, 0x37,
	0x32, 0x18, 0x0a, 0xed, 0x90, 0xd8, 0xda, 0x0b, 0x29, 0xdf, 0xca, 0x4f, 0x2a, 0xd0, 0x9a, 0x6d,
	0x2d, 0x64, 0xe8, 0x44, 0x5a, 0xed, 0xa8, 0x50, 0x68, 0x87, 0x44, 0x2b, 0xf4, 0x9d, 0x06, 0x3e,
	0x50, 0xc0, 0x51, 0xd0, 0x9e, 0xae, 0x85, 0x5c, 0x06, 0x39, 0x2b, 0xf2, 0x47, 0x77, 0xa8, 0x76,
	0xab, 0xb5, 0xf4, 0x2a, 0x9a, 0xe6, 0x2e, 0xa8, 0x18, 0xab, 0x35, 0xfa, 0x0a, 0xcc, 0x13, 0xa7,
	0x95, 0x4b, 0x15, 0x00, 0x2b, 0xb8, 0xe1, 0xb4, 0x22, 0xca, 0xf2, 0xff, 0xec, 0xe8, 0x67, 0x7b,
	0x07, 0xe7, 0xd1, 0xe2, 0x36, 0x4a, 0xf0, 0x86, 0xe0, 0x19, 0x8e, 0x6e, 0x71, 0xe8, 0xbc, 0x41,
	0x5f, 0xc2, 0xbb, 0xe9, 0x6c, 0xb6, 0xbc, 0x59, 0x24, 0x9b, 0x15, 0xc6, 0x64, 0xf3, 0xe3, 0x32,
	0x5a, 0xe0, 0xd0, 0x31, 0xd0, 0x17, 0xf0, 0xf6, 0x45, 0x61, 0x8e, 0xaf, 0x13, 0x67, 0x80, 0xce,
	0xc1, 0x6e, 0xf7, 0x75, 0xd0, 0x19, 0x0c, 0x9f, 0xeb, 0x5d, 0xf4, 0x16, 0xce, 0x62, 0xbc, 0x5e,
	0x4f, 0x7f, 0xc0, 0x9b, 0x69, 0x18, 0xe2, 0xd0, 0x31, 0xe5, 0x16, 0x19, 0x97, 0xb5, 0x36, 0x2c,
	0xd9, 0x33, 0x5b, 0xc6, 0x31, 0x5e, 0x24, 0xda, 0xea, 0xa1, 0x31, 0xc0, 0x3c, 0xfa, 0xa9, 0xd9,
	0xd3, 0x97, 0x7b, 0xa6, 0x61, 0x1c, 0x2d, 0xb4, 0x91, 0x23, 0x07, 0x46, 0xea, 0x18, 0x82, 0xe3,
	0xa5, 0xbc, 0x39, 0x95, 0x2d, 0x2a, 0x6e, 0xba, 0xe5, 0x4e, 0xb6, 0xac, 0x13, 0x82, 0xa7, 0xb1,
	0x76, 0x76, 0xe8, 0x3d, 0x38, 0xeb, 0x28, 0x5e, 0xcd, 0xb1, 0x3c, 0x5f, 0xbb, 0xbf, 0x20, 0x07,
	0x6c, 0xdd, 0xa7, 0x52, 0xfc, 0x77, 0x17, 0x21, 0x38, 0x23, 0x78, 0xb6, 0x24, 0xe1, 0x86, 0xe0,
	0xd5, 0x92, 0x24, 0xce, 0x3f, 0x5d, 0x7f, 0x0e, 0xa6, 0x84, 0x28, 0x43, 0x91, 0xe6, 0x79, 0x45,
	0x39, 0xd7, 0x79, 0x6b, 0xa4, 0x7c, 0x87, 0x63, 0x7a, 0xa0, 0xfa, 0x97, 0xa4, 0xd6, 0xf2, 0xbd,
	0xd3, 0xdf, 0x52, 0x91, 0x36, 0xc9, 0xd2, 0xea, 0xea, 0x6b, 0xf8, 0xc0, 0xef, 0xc5, 0x29, 0x28,
	0x4a, 0x7a, 0x3c, 0x52, 0x11, 0x08, 0xfa, 0x20, 0xd8, 0x9e, 0x96, 0xd9, 0xcf, 0x9d, 0x32, 0xcb,
	0x7a, 0x2a, 0xa8, 0x9f, 0xff, 0x0b, 0x00, 0x00, 0xff, 0xff, 0xbc, 0x9a, 0x99, 0x84, 0x37, 0x05,
	0x00, 0x00,
}
