// Code generated by protoc-gen-go. DO NOT EDIT.
// source: model.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type StreamBlock struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Streamid             string   `protobuf:"bytes,2,opt,name=streamid,proto3" json:"streamid,omitempty"`
	Index                uint64   `protobuf:"varint,3,opt,name=index,proto3" json:"index,omitempty"`
	Size                 int32    `protobuf:"varint,4,opt,name=size,proto3" json:"size,omitempty"`
	IsRoot               bool     `protobuf:"varint,5,opt,name=isRoot,proto3" json:"isRoot,omitempty"`
	Description          string   `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StreamBlock) Reset()         { *m = StreamBlock{} }
func (m *StreamBlock) String() string { return proto.CompactTextString(m) }
func (*StreamBlock) ProtoMessage()    {}
func (*StreamBlock) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c16552f9fdb66d8, []int{0}
}

func (m *StreamBlock) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StreamBlock.Unmarshal(m, b)
}
func (m *StreamBlock) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StreamBlock.Marshal(b, m, deterministic)
}
func (m *StreamBlock) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StreamBlock.Merge(m, src)
}
func (m *StreamBlock) XXX_Size() int {
	return xxx_messageInfo_StreamBlock.Size(m)
}
func (m *StreamBlock) XXX_DiscardUnknown() {
	xxx_messageInfo_StreamBlock.DiscardUnknown(m)
}

var xxx_messageInfo_StreamBlock proto.InternalMessageInfo

func (m *StreamBlock) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *StreamBlock) GetStreamid() string {
	if m != nil {
		return m.Streamid
	}
	return ""
}

func (m *StreamBlock) GetIndex() uint64 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *StreamBlock) GetSize() int32 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *StreamBlock) GetIsRoot() bool {
	if m != nil {
		return m.IsRoot
	}
	return false
}

func (m *StreamBlock) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

type StreamBlockList struct {
	Items                []*StreamBlock `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *StreamBlockList) Reset()         { *m = StreamBlockList{} }
func (m *StreamBlockList) String() string { return proto.CompactTextString(m) }
func (*StreamBlockList) ProtoMessage()    {}
func (*StreamBlockList) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c16552f9fdb66d8, []int{1}
}

func (m *StreamBlockList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StreamBlockList.Unmarshal(m, b)
}
func (m *StreamBlockList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StreamBlockList.Marshal(b, m, deterministic)
}
func (m *StreamBlockList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StreamBlockList.Merge(m, src)
}
func (m *StreamBlockList) XXX_Size() int {
	return xxx_messageInfo_StreamBlockList.Size(m)
}
func (m *StreamBlockList) XXX_DiscardUnknown() {
	xxx_messageInfo_StreamBlockList.DiscardUnknown(m)
}

var xxx_messageInfo_StreamBlockList proto.InternalMessageInfo

func (m *StreamBlockList) GetItems() []*StreamBlock {
	if m != nil {
		return m.Items
	}
	return nil
}

type StreamMeta struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Nsubstreams          int32    `protobuf:"varint,2,opt,name=nsubstreams,proto3" json:"nsubstreams,omitempty"`
	Bitrate              int32    `protobuf:"varint,3,opt,name=bitrate,proto3" json:"bitrate,omitempty"`
	Caption              string   `protobuf:"bytes,4,opt,name=caption,proto3" json:"caption,omitempty"`
	Nblocks              uint64   `protobuf:"varint,5,opt,name=nblocks,proto3" json:"nblocks,omitempty"`
	Posterid             string   `protobuf:"bytes,6,opt,name=posterid,proto3" json:"posterid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StreamMeta) Reset()         { *m = StreamMeta{} }
func (m *StreamMeta) String() string { return proto.CompactTextString(m) }
func (*StreamMeta) ProtoMessage()    {}
func (*StreamMeta) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c16552f9fdb66d8, []int{2}
}

func (m *StreamMeta) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StreamMeta.Unmarshal(m, b)
}
func (m *StreamMeta) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StreamMeta.Marshal(b, m, deterministic)
}
func (m *StreamMeta) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StreamMeta.Merge(m, src)
}
func (m *StreamMeta) XXX_Size() int {
	return xxx_messageInfo_StreamMeta.Size(m)
}
func (m *StreamMeta) XXX_DiscardUnknown() {
	xxx_messageInfo_StreamMeta.DiscardUnknown(m)
}

var xxx_messageInfo_StreamMeta proto.InternalMessageInfo

func (m *StreamMeta) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *StreamMeta) GetNsubstreams() int32 {
	if m != nil {
		return m.Nsubstreams
	}
	return 0
}

func (m *StreamMeta) GetBitrate() int32 {
	if m != nil {
		return m.Bitrate
	}
	return 0
}

func (m *StreamMeta) GetCaption() string {
	if m != nil {
		return m.Caption
	}
	return ""
}

func (m *StreamMeta) GetNblocks() uint64 {
	if m != nil {
		return m.Nblocks
	}
	return 0
}

func (m *StreamMeta) GetPosterid() string {
	if m != nil {
		return m.Posterid
	}
	return ""
}

type StreamMetaList struct {
	Items                []*StreamMeta `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *StreamMetaList) Reset()         { *m = StreamMetaList{} }
func (m *StreamMetaList) String() string { return proto.CompactTextString(m) }
func (*StreamMetaList) ProtoMessage()    {}
func (*StreamMetaList) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c16552f9fdb66d8, []int{3}
}

func (m *StreamMetaList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StreamMetaList.Unmarshal(m, b)
}
func (m *StreamMetaList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StreamMetaList.Marshal(b, m, deterministic)
}
func (m *StreamMetaList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StreamMetaList.Merge(m, src)
}
func (m *StreamMetaList) XXX_Size() int {
	return xxx_messageInfo_StreamMetaList.Size(m)
}
func (m *StreamMetaList) XXX_DiscardUnknown() {
	xxx_messageInfo_StreamMetaList.DiscardUnknown(m)
}

var xxx_messageInfo_StreamMetaList proto.InternalMessageInfo

func (m *StreamMetaList) GetItems() []*StreamMeta {
	if m != nil {
		return m.Items
	}
	return nil
}

// [deprecated] use streamMeta directly
type Stream struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Stream) Reset()         { *m = Stream{} }
func (m *Stream) String() string { return proto.CompactTextString(m) }
func (*Stream) ProtoMessage()    {}
func (*Stream) Descriptor() ([]byte, []int) {
	return fileDescriptor_4c16552f9fdb66d8, []int{4}
}

func (m *Stream) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Stream.Unmarshal(m, b)
}
func (m *Stream) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Stream.Marshal(b, m, deterministic)
}
func (m *Stream) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Stream.Merge(m, src)
}
func (m *Stream) XXX_Size() int {
	return xxx_messageInfo_Stream.Size(m)
}
func (m *Stream) XXX_DiscardUnknown() {
	xxx_messageInfo_Stream.DiscardUnknown(m)
}

var xxx_messageInfo_Stream proto.InternalMessageInfo

func (m *Stream) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func init() {
	proto.RegisterType((*StreamBlock)(nil), "StreamBlock")
	proto.RegisterType((*StreamBlockList)(nil), "StreamBlockList")
	proto.RegisterType((*StreamMeta)(nil), "StreamMeta")
	proto.RegisterType((*StreamMetaList)(nil), "StreamMetaList")
	proto.RegisterType((*Stream)(nil), "Stream")
}

func init() { proto.RegisterFile("model.proto", fileDescriptor_4c16552f9fdb66d8) }

var fileDescriptor_4c16552f9fdb66d8 = []byte{
	// 305 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x91, 0xb1, 0x6e, 0xb3, 0x30,
	0x14, 0x85, 0x65, 0x02, 0xfc, 0xf9, 0x2f, 0x55, 0x2a, 0x59, 0x55, 0x64, 0x55, 0x1d, 0x5c, 0x26,
	0x26, 0x86, 0x46, 0x7d, 0x81, 0xcc, 0xed, 0xe2, 0x6e, 0xdd, 0x20, 0xbe, 0xc3, 0x6d, 0x03, 0x46,
	0xf8, 0x46, 0x8a, 0xfa, 0x2e, 0xdd, 0xfb, 0x98, 0x15, 0x26, 0x24, 0xb4, 0xdd, 0xf8, 0xce, 0x41,
	0x70, 0x3e, 0x1b, 0xb2, 0xc6, 0x59, 0xdc, 0x97, 0x5d, 0xef, 0xd8, 0xe5, 0x9f, 0x02, 0xb2, 0x17,
	0xee, 0xb1, 0x6a, 0xb6, 0x7b, 0xb7, 0x7b, 0x97, 0x2b, 0x88, 0xc8, 0x2a, 0xa1, 0x45, 0xf1, 0xdf,
	0x44, 0x64, 0xe5, 0x2d, 0x2c, 0x7d, 0xa8, 0xc9, 0xaa, 0x28, 0xa4, 0x67, 0x96, 0x37, 0x90, 0x50,
	0x6b, 0xf1, 0xa8, 0x16, 0x5a, 0x14, 0xb1, 0x19, 0x41, 0x4a, 0x88, 0x3d, 0x7d, 0xa0, 0x8a, 0xb5,
	0x28, 0x12, 0x13, 0x9e, 0xe5, 0x1a, 0x52, 0xf2, 0xc6, 0x39, 0x56, 0x89, 0x16, 0xc5, 0xd2, 0x9c,
	0x48, 0x6a, 0xc8, 0x2c, 0xfa, 0x5d, 0x4f, 0x1d, 0x93, 0x6b, 0x55, 0x1a, 0x7e, 0x30, 0x8f, 0xf2,
	0x47, 0xb8, 0x9e, 0xcd, 0x7b, 0x22, 0xcf, 0x32, 0x87, 0x84, 0x18, 0x1b, 0xaf, 0x84, 0x5e, 0x14,
	0xd9, 0xc3, 0x55, 0x39, 0x7b, 0xc1, 0x8c, 0x55, 0xfe, 0x25, 0x00, 0xc6, 0xf8, 0x19, 0xb9, 0xfa,
	0x63, 0xa5, 0x21, 0x6b, 0xfd, 0xa1, 0x1e, 0x4d, 0x7c, 0x10, 0x4b, 0xcc, 0x3c, 0x92, 0x0a, 0xfe,
	0xd5, 0xc4, 0x7d, 0xc5, 0x18, 0xec, 0x12, 0x33, 0xe1, 0xd0, 0xec, 0xaa, 0x71, 0x6f, 0x1c, 0x3e,
	0x38, 0xe1, 0xd0, 0xb4, 0xf5, 0xb0, 0xc2, 0x07, 0xcd, 0xd8, 0x4c, 0x38, 0x9c, 0x62, 0xe7, 0x3c,
	0x63, 0x4f, 0xf6, 0x24, 0x79, 0xe6, 0x7c, 0x03, 0xab, 0xcb, 0xd2, 0x20, 0x78, 0xff, 0x53, 0x30,
	0x2b, 0x2f, 0xfd, 0xe4, 0xa7, 0x20, 0x1d, 0xc3, 0xdf, 0x6a, 0xdb, 0x3b, 0x58, 0xfb, 0x37, 0x3e,
	0x94, 0xae, 0xc3, 0xb6, 0x45, 0x2e, 0x19, 0x8f, 0x4c, 0x7b, 0xec, 0xea, 0xd7, 0xa8, 0xab, 0xeb,
	0x34, 0xdc, 0xfa, 0xe6, 0x3b, 0x00, 0x00, 0xff, 0xff, 0x2f, 0xd1, 0x70, 0x07, 0x04, 0x02, 0x00,
	0x00,
}
