// Code generated by protoc-gen-go. DO NOT EDIT.
// source: shadow_service.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ShadowInform struct {
	PublicKey            string   `protobuf:"bytes,1,opt,name=publicKey,proto3" json:"publicKey,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ShadowInform) Reset()         { *m = ShadowInform{} }
func (m *ShadowInform) String() string { return proto.CompactTextString(m) }
func (*ShadowInform) ProtoMessage()    {}
func (*ShadowInform) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b707f8c1934294c, []int{0}
}

func (m *ShadowInform) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShadowInform.Unmarshal(m, b)
}
func (m *ShadowInform) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShadowInform.Marshal(b, m, deterministic)
}
func (m *ShadowInform) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShadowInform.Merge(m, src)
}
func (m *ShadowInform) XXX_Size() int {
	return xxx_messageInfo_ShadowInform.Size(m)
}
func (m *ShadowInform) XXX_DiscardUnknown() {
	xxx_messageInfo_ShadowInform.DiscardUnknown(m)
}

var xxx_messageInfo_ShadowInform proto.InternalMessageInfo

func (m *ShadowInform) GetPublicKey() string {
	if m != nil {
		return m.PublicKey
	}
	return ""
}

type ShadowInformResponse struct {
	Accept               bool     `protobuf:"varint,1,opt,name=accept,proto3" json:"accept,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ShadowInformResponse) Reset()         { *m = ShadowInformResponse{} }
func (m *ShadowInformResponse) String() string { return proto.CompactTextString(m) }
func (*ShadowInformResponse) ProtoMessage()    {}
func (*ShadowInformResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b707f8c1934294c, []int{1}
}

func (m *ShadowInformResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShadowInformResponse.Unmarshal(m, b)
}
func (m *ShadowInformResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShadowInformResponse.Marshal(b, m, deterministic)
}
func (m *ShadowInformResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShadowInformResponse.Merge(m, src)
}
func (m *ShadowInformResponse) XXX_Size() int {
	return xxx_messageInfo_ShadowInformResponse.Size(m)
}
func (m *ShadowInformResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ShadowInformResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ShadowInformResponse proto.InternalMessageInfo

func (m *ShadowInformResponse) GetAccept() bool {
	if m != nil {
		return m.Accept
	}
	return false
}

type ShadowStat struct {
	Role                 string   `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"`
	Shadow               string   `protobuf:"bytes,2,opt,name=shadow,proto3" json:"shadow,omitempty"`
	Users                []string `protobuf:"bytes,3,rep,name=users,proto3" json:"users,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ShadowStat) Reset()         { *m = ShadowStat{} }
func (m *ShadowStat) String() string { return proto.CompactTextString(m) }
func (*ShadowStat) ProtoMessage()    {}
func (*ShadowStat) Descriptor() ([]byte, []int) {
	return fileDescriptor_2b707f8c1934294c, []int{2}
}

func (m *ShadowStat) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShadowStat.Unmarshal(m, b)
}
func (m *ShadowStat) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShadowStat.Marshal(b, m, deterministic)
}
func (m *ShadowStat) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShadowStat.Merge(m, src)
}
func (m *ShadowStat) XXX_Size() int {
	return xxx_messageInfo_ShadowStat.Size(m)
}
func (m *ShadowStat) XXX_DiscardUnknown() {
	xxx_messageInfo_ShadowStat.DiscardUnknown(m)
}

var xxx_messageInfo_ShadowStat proto.InternalMessageInfo

func (m *ShadowStat) GetRole() string {
	if m != nil {
		return m.Role
	}
	return ""
}

func (m *ShadowStat) GetShadow() string {
	if m != nil {
		return m.Shadow
	}
	return ""
}

func (m *ShadowStat) GetUsers() []string {
	if m != nil {
		return m.Users
	}
	return nil
}

func init() {
	proto.RegisterType((*ShadowInform)(nil), "ShadowInform")
	proto.RegisterType((*ShadowInformResponse)(nil), "ShadowInformResponse")
	proto.RegisterType((*ShadowStat)(nil), "ShadowStat")
}

func init() { proto.RegisterFile("shadow_service.proto", fileDescriptor_2b707f8c1934294c) }

var fileDescriptor_2b707f8c1934294c = []byte{
	// 194 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x8f, 0x3d, 0x8b, 0x83, 0x40,
	0x10, 0x86, 0x51, 0xef, 0xe4, 0x1c, 0xae, 0x5a, 0x44, 0x2c, 0x2c, 0xc4, 0xca, 0xe2, 0xd8, 0xe6,
	0xfe, 0x41, 0xba, 0x10, 0x48, 0xb1, 0x76, 0x69, 0x82, 0xbb, 0x99, 0x10, 0x83, 0xd9, 0x5d, 0x76,
	0xc7, 0x7c, 0xfc, 0xfb, 0x90, 0x55, 0x48, 0xba, 0x79, 0x1e, 0xde, 0x77, 0x98, 0x81, 0xdc, 0x9f,
	0xfa, 0x83, 0xb9, 0xed, 0x3d, 0xba, 0xeb, 0xa0, 0x90, 0x5b, 0x67, 0xc8, 0x34, 0x7f, 0xf0, 0xdb,
	0x05, 0xbf, 0xd6, 0x47, 0xe3, 0x2e, 0xac, 0x82, 0xcc, 0x4e, 0x72, 0x1c, 0xd4, 0x06, 0x1f, 0x65,
	0x54, 0x47, 0x6d, 0x26, 0xde, 0xa2, 0xe1, 0x90, 0x7f, 0xa6, 0x05, 0x7a, 0x6b, 0xb4, 0x47, 0x56,
	0x40, 0xda, 0x2b, 0x85, 0x96, 0x42, 0xe5, 0x47, 0x2c, 0xd4, 0x6c, 0x01, 0xe6, 0x7c, 0x47, 0x3d,
	0x31, 0x06, 0x5f, 0xce, 0x8c, 0xb8, 0xac, 0x0d, 0xf3, 0xab, 0x39, 0xdf, 0x55, 0xc6, 0xc1, 0x2e,
	0xc4, 0x72, 0xf8, 0x9e, 0x3c, 0x3a, 0x5f, 0x26, 0x75, 0xd2, 0x66, 0x62, 0x86, 0x55, 0x05, 0x85,
	0x3f, 0xd3, 0xc4, 0x8d, 0x45, 0xad, 0x91, 0x38, 0xe1, 0x9d, 0x86, 0x11, 0xad, 0xdc, 0xc5, 0x56,
	0xca, 0x34, 0xbc, 0xf4, 0xff, 0x0c, 0x00, 0x00, 0xff, 0xff, 0xa7, 0xb8, 0x94, 0x2d, 0xea, 0x00,
	0x00, 0x00,
}
