// Code generated by protoc-gen-go. DO NOT EDIT.
// source: stream_service.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// StreamBlockContent is used for transmitting stream block in stream service
// the description is used for store CID due to the lack of ipfs interfaces in switches
type StreamBlockContent struct {
	StreamID             string   `protobuf:"bytes,1,opt,name=streamID,proto3" json:"streamID,omitempty"`
	Index                uint64   `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"`
	Data                 []byte   `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	IsRoot               bool     `protobuf:"varint,4,opt,name=isRoot,proto3" json:"isRoot,omitempty"`
	Description          string   `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StreamBlockContent) Reset()         { *m = StreamBlockContent{} }
func (m *StreamBlockContent) String() string { return proto.CompactTextString(m) }
func (*StreamBlockContent) ProtoMessage()    {}
func (*StreamBlockContent) Descriptor() ([]byte, []int) {
	return fileDescriptor_296dc607c23b8aea, []int{0}
}

func (m *StreamBlockContent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StreamBlockContent.Unmarshal(m, b)
}
func (m *StreamBlockContent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StreamBlockContent.Marshal(b, m, deterministic)
}
func (m *StreamBlockContent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StreamBlockContent.Merge(m, src)
}
func (m *StreamBlockContent) XXX_Size() int {
	return xxx_messageInfo_StreamBlockContent.Size(m)
}
func (m *StreamBlockContent) XXX_DiscardUnknown() {
	xxx_messageInfo_StreamBlockContent.DiscardUnknown(m)
}

var xxx_messageInfo_StreamBlockContent proto.InternalMessageInfo

func (m *StreamBlockContent) GetStreamID() string {
	if m != nil {
		return m.StreamID
	}
	return ""
}

func (m *StreamBlockContent) GetIndex() uint64 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *StreamBlockContent) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *StreamBlockContent) GetIsRoot() bool {
	if m != nil {
		return m.IsRoot
	}
	return false
}

func (m *StreamBlockContent) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

type StreamBlockContentList struct {
	Blocks               []*StreamBlockContent `protobuf:"bytes,1,rep,name=blocks,proto3" json:"blocks,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *StreamBlockContentList) Reset()         { *m = StreamBlockContentList{} }
func (m *StreamBlockContentList) String() string { return proto.CompactTextString(m) }
func (*StreamBlockContentList) ProtoMessage()    {}
func (*StreamBlockContentList) Descriptor() ([]byte, []int) {
	return fileDescriptor_296dc607c23b8aea, []int{1}
}

func (m *StreamBlockContentList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StreamBlockContentList.Unmarshal(m, b)
}
func (m *StreamBlockContentList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StreamBlockContentList.Marshal(b, m, deterministic)
}
func (m *StreamBlockContentList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StreamBlockContentList.Merge(m, src)
}
func (m *StreamBlockContentList) XXX_Size() int {
	return xxx_messageInfo_StreamBlockContentList.Size(m)
}
func (m *StreamBlockContentList) XXX_DiscardUnknown() {
	xxx_messageInfo_StreamBlockContentList.DiscardUnknown(m)
}

var xxx_messageInfo_StreamBlockContentList proto.InternalMessageInfo

func (m *StreamBlockContentList) GetBlocks() []*StreamBlockContent {
	if m != nil {
		return m.Blocks
	}
	return nil
}

type StreamRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	StreamMap            uint64   `protobuf:"varint,2,opt,name=streamMap,proto3" json:"streamMap,omitempty"`
	StartIndex           uint64   `protobuf:"varint,3,opt,name=startIndex,proto3" json:"startIndex,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StreamRequest) Reset()         { *m = StreamRequest{} }
func (m *StreamRequest) String() string { return proto.CompactTextString(m) }
func (*StreamRequest) ProtoMessage()    {}
func (*StreamRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_296dc607c23b8aea, []int{2}
}

func (m *StreamRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StreamRequest.Unmarshal(m, b)
}
func (m *StreamRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StreamRequest.Marshal(b, m, deterministic)
}
func (m *StreamRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StreamRequest.Merge(m, src)
}
func (m *StreamRequest) XXX_Size() int {
	return xxx_messageInfo_StreamRequest.Size(m)
}
func (m *StreamRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StreamRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StreamRequest proto.InternalMessageInfo

func (m *StreamRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *StreamRequest) GetStreamMap() uint64 {
	if m != nil {
		return m.StreamMap
	}
	return 0
}

func (m *StreamRequest) GetStartIndex() uint64 {
	if m != nil {
		return m.StartIndex
	}
	return 0
}

type StreamRequestHandle struct {
	Value                uint64   `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StreamRequestHandle) Reset()         { *m = StreamRequestHandle{} }
func (m *StreamRequestHandle) String() string { return proto.CompactTextString(m) }
func (*StreamRequestHandle) ProtoMessage()    {}
func (*StreamRequestHandle) Descriptor() ([]byte, []int) {
	return fileDescriptor_296dc607c23b8aea, []int{3}
}

func (m *StreamRequestHandle) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StreamRequestHandle.Unmarshal(m, b)
}
func (m *StreamRequestHandle) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StreamRequestHandle.Marshal(b, m, deterministic)
}
func (m *StreamRequestHandle) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StreamRequestHandle.Merge(m, src)
}
func (m *StreamRequestHandle) XXX_Size() int {
	return xxx_messageInfo_StreamRequestHandle.Size(m)
}
func (m *StreamRequestHandle) XXX_DiscardUnknown() {
	xxx_messageInfo_StreamRequestHandle.DiscardUnknown(m)
}

var xxx_messageInfo_StreamRequestHandle proto.InternalMessageInfo

func (m *StreamRequestHandle) GetValue() uint64 {
	if m != nil {
		return m.Value
	}
	return 0
}

type StreamUnsubscribe struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StreamUnsubscribe) Reset()         { *m = StreamUnsubscribe{} }
func (m *StreamUnsubscribe) String() string { return proto.CompactTextString(m) }
func (*StreamUnsubscribe) ProtoMessage()    {}
func (*StreamUnsubscribe) Descriptor() ([]byte, []int) {
	return fileDescriptor_296dc607c23b8aea, []int{4}
}

func (m *StreamUnsubscribe) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StreamUnsubscribe.Unmarshal(m, b)
}
func (m *StreamUnsubscribe) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StreamUnsubscribe.Marshal(b, m, deterministic)
}
func (m *StreamUnsubscribe) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StreamUnsubscribe.Merge(m, src)
}
func (m *StreamUnsubscribe) XXX_Size() int {
	return xxx_messageInfo_StreamUnsubscribe.Size(m)
}
func (m *StreamUnsubscribe) XXX_DiscardUnknown() {
	xxx_messageInfo_StreamUnsubscribe.DiscardUnknown(m)
}

var xxx_messageInfo_StreamUnsubscribe proto.InternalMessageInfo

func (m *StreamUnsubscribe) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type StreamUnsubscribeAck struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StreamUnsubscribeAck) Reset()         { *m = StreamUnsubscribeAck{} }
func (m *StreamUnsubscribeAck) String() string { return proto.CompactTextString(m) }
func (*StreamUnsubscribeAck) ProtoMessage()    {}
func (*StreamUnsubscribeAck) Descriptor() ([]byte, []int) {
	return fileDescriptor_296dc607c23b8aea, []int{5}
}

func (m *StreamUnsubscribeAck) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StreamUnsubscribeAck.Unmarshal(m, b)
}
func (m *StreamUnsubscribeAck) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StreamUnsubscribeAck.Marshal(b, m, deterministic)
}
func (m *StreamUnsubscribeAck) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StreamUnsubscribeAck.Merge(m, src)
}
func (m *StreamUnsubscribeAck) XXX_Size() int {
	return xxx_messageInfo_StreamUnsubscribeAck.Size(m)
}
func (m *StreamUnsubscribeAck) XXX_DiscardUnknown() {
	xxx_messageInfo_StreamUnsubscribeAck.DiscardUnknown(m)
}

var xxx_messageInfo_StreamUnsubscribeAck proto.InternalMessageInfo

func (m *StreamUnsubscribeAck) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

// StreamClose is used to tell other peers that a stream is closed.
//  - streamId: Id of stream.
//  - maxIndex: Maximum index of blocks.
//              Receiver will detect the lost blocks according to it.
type StreamClose struct {
	StreamId             string   `protobuf:"bytes,1,opt,name=streamId,proto3" json:"streamId,omitempty"`
	MaxIndex             uint64   `protobuf:"varint,2,opt,name=maxIndex,proto3" json:"maxIndex,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StreamClose) Reset()         { *m = StreamClose{} }
func (m *StreamClose) String() string { return proto.CompactTextString(m) }
func (*StreamClose) ProtoMessage()    {}
func (*StreamClose) Descriptor() ([]byte, []int) {
	return fileDescriptor_296dc607c23b8aea, []int{6}
}

func (m *StreamClose) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StreamClose.Unmarshal(m, b)
}
func (m *StreamClose) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StreamClose.Marshal(b, m, deterministic)
}
func (m *StreamClose) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StreamClose.Merge(m, src)
}
func (m *StreamClose) XXX_Size() int {
	return xxx_messageInfo_StreamClose.Size(m)
}
func (m *StreamClose) XXX_DiscardUnknown() {
	xxx_messageInfo_StreamClose.DiscardUnknown(m)
}

var xxx_messageInfo_StreamClose proto.InternalMessageInfo

func (m *StreamClose) GetStreamId() string {
	if m != nil {
		return m.StreamId
	}
	return ""
}

func (m *StreamClose) GetMaxIndex() uint64 {
	if m != nil {
		return m.MaxIndex
	}
	return 0
}

func init() {
	proto.RegisterType((*StreamBlockContent)(nil), "StreamBlockContent")
	proto.RegisterType((*StreamBlockContentList)(nil), "StreamBlockContentList")
	proto.RegisterType((*StreamRequest)(nil), "StreamRequest")
	proto.RegisterType((*StreamRequestHandle)(nil), "StreamRequestHandle")
	proto.RegisterType((*StreamUnsubscribe)(nil), "StreamUnsubscribe")
	proto.RegisterType((*StreamUnsubscribeAck)(nil), "StreamUnsubscribeAck")
	proto.RegisterType((*StreamClose)(nil), "StreamClose")
}

func init() { proto.RegisterFile("stream_service.proto", fileDescriptor_296dc607c23b8aea) }

var fileDescriptor_296dc607c23b8aea = []byte{
	// 337 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x92, 0x5f, 0x6b, 0xe2, 0x40,
	0x14, 0xc5, 0x49, 0x8c, 0xa2, 0xd7, 0xdd, 0x85, 0x1d, 0x45, 0xc2, 0x22, 0x4b, 0xc8, 0xc2, 0x12,
	0x10, 0xf2, 0xd0, 0x7e, 0x82, 0x6a, 0x85, 0x0a, 0xed, 0xcb, 0x94, 0xbe, 0x14, 0x4a, 0x99, 0x64,
	0xee, 0xc3, 0xd4, 0x38, 0x93, 0x66, 0x6e, 0xc4, 0x0f, 0xd2, 0x0f, 0x5c, 0xf2, 0x07, 0x9b, 0x9a,
	0xb7, 0x9c, 0x73, 0x7e, 0xe4, 0xde, 0x93, 0x1b, 0x98, 0x5b, 0x2a, 0x50, 0x1c, 0x5e, 0x2d, 0x16,
	0x47, 0x95, 0x62, 0x9c, 0x17, 0x86, 0x4c, 0xf8, 0xe1, 0x00, 0x7b, 0xac, 0x83, 0x75, 0x66, 0xd2,
	0xfd, 0xc6, 0x68, 0x42, 0x4d, 0xec, 0x0f, 0x8c, 0x1b, 0x7c, 0x77, 0xeb, 0x3b, 0x81, 0x13, 0x4d,
	0xf8, 0x59, 0xb3, 0x39, 0x0c, 0x95, 0x96, 0x78, 0xf2, 0xdd, 0xc0, 0x89, 0x3c, 0xde, 0x08, 0xc6,
	0xc0, 0x93, 0x82, 0x84, 0x3f, 0x08, 0x9c, 0xe8, 0x07, 0xaf, 0x9f, 0xd9, 0x02, 0x46, 0xca, 0x72,
	0x63, 0xc8, 0xf7, 0x02, 0x27, 0x1a, 0xf3, 0x56, 0xb1, 0x00, 0xa6, 0x12, 0x6d, 0x5a, 0xa8, 0x9c,
	0x94, 0xd1, 0xfe, 0xb0, 0x1e, 0xd0, 0xb5, 0xc2, 0x2d, 0x2c, 0xfa, 0x5b, 0xdd, 0x2b, 0x4b, 0x6c,
	0x05, 0xa3, 0xa4, 0xf2, 0xac, 0xef, 0x04, 0x83, 0x68, 0x7a, 0x35, 0x8b, 0xfb, 0x20, 0x6f, 0x91,
	0xf0, 0x05, 0x7e, 0x36, 0x29, 0xc7, 0xf7, 0x12, 0x2d, 0xb1, 0x5f, 0xe0, 0x2a, 0xd9, 0x36, 0x72,
	0x95, 0x64, 0x4b, 0x98, 0x34, 0xbd, 0x1e, 0x44, 0xde, 0xf6, 0xf9, 0x32, 0xd8, 0x5f, 0x00, 0x4b,
	0xa2, 0xa0, 0x5d, 0x5d, 0x77, 0x50, 0xc7, 0x1d, 0x27, 0x5c, 0xc1, 0xec, 0xdb, 0xeb, 0xef, 0x84,
	0x96, 0x19, 0x56, 0x1f, 0xe8, 0x28, 0xb2, 0x12, 0xeb, 0x39, 0x1e, 0x6f, 0x44, 0xf8, 0x0f, 0x7e,
	0x37, 0xf0, 0x93, 0xb6, 0x65, 0x52, 0x55, 0x4d, 0xf0, 0x72, 0x9f, 0xf0, 0x3f, 0xcc, 0x7b, 0xd0,
	0x4d, 0xba, 0xef, 0x71, 0x5b, 0x98, 0x36, 0xdc, 0x26, 0x33, 0x16, 0x3b, 0xe7, 0x92, 0x17, 0xe7,
	0x92, 0x55, 0x76, 0x10, 0xa7, 0x5d, 0xe7, 0x62, 0x67, 0xbd, 0x5e, 0xc2, 0xc2, 0xbe, 0x51, 0x19,
	0x9b, 0x1c, 0xb5, 0x46, 0x8a, 0x09, 0x4f, 0xa4, 0x32, 0xcc, 0x93, 0x67, 0x37, 0x4f, 0x92, 0x51,
	0xfd, 0x8b, 0x5c, 0x7f, 0x06, 0x00, 0x00, 0xff, 0xff, 0xcf, 0x3a, 0xf9, 0x5e, 0x3a, 0x02, 0x00,
	0x00,
}
